Homework6
================
Chirag Shah
2018-11-27

``` r
library(tidyverse)
library(rvest)
library(purrr)
#set.seed(1)
```

``` r
homicides = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

``` r
##reading in data from github 
```

The dataset contains 52179 reports on homicides and 12 variables. The homicide information contained in this dataset shows us the data for homicides in 50 US cities for a decade.

``` r
homicides = homicides %>% 
  unite("city_state", c("city", "state"), sep = ", ", remove = TRUE) %>% 
##creating city_state variable by uniting the city and state 
  mutate(solved = as.numeric(disposition == "Closed by arrest"), 
         victim_race = ifelse(victim_race != "White", "non-White", "White"),  
         victim_race = fct_relevel(victim_race, "White", "non-White"),
         victim_age = as.numeric(victim_age)) %>% 
##creating binary variable for whether the case was solved or not
##changing victim_race so that it is either non-White or White and ensuring White is the reference group
##making victim_age a numeric variable
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

``` r
##filtering out unwanted observations
```

Logit Modeling
--------------

``` r
baltimore_model = homicides %>% 
##running glm only on Baltimore
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_sex + victim_race + victim_age, family = binomial, data = .)

broom::tidy(baltimore_model) %>% 
  mutate(odds_ratio = exp(estimate), 
         lower_bound = exp(estimate - 1.96*std.error), 
         upper_bound = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_racenon-White") %>% 
  select(odds_ratio, lower_bound, upper_bound) %>% 
  knitr::kable(digits = 3)
```

|  odds\_ratio|  lower\_bound|  upper\_bound|
|------------:|-------------:|-------------:|
|        0.441|         0.313|          0.62|

In Baltimore, among non-white victims, the odds of having a solved homicide is 0.441 times the odds of having a solved homicide among white victims. We are 95% confident that the true odds ratio lies between 0.313 and 0.620.

Now run glm for each of the cities in your dataset, and extract the adjusted odds ratio (and CI) for solving homicides comparing non-white victims to white victims. Do this within a “tidy” pipeline, making use of purrr::map, list columns, and unnest as necessary to create a dataframe with estimated ORs and CIs for each city.

Create a plot that shows the estimated ORs and CIs for each city. Organize cities according to estimated OR, and comment on the plot.

Problem 2

In this probelm, you will analyze data gathered to understand the effects of several variables on a child’s birthweight. This dataset, available here, consists of roughly 4000 children and includes the following variables:

    babysex: baby’s sex (male = 1, female = 2)
    bhead: baby’s head circumference at birth (centimeters)
    blength: baby’s length at birth (centimeteres)
    bwt: baby’s birth weight (grams)
    delwt: mother’s weight at delivery (pounds)
    fincome: family monthly income (in hundreds, rounded)
    frace: father’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other, 9 = Unknown)
    gaweeks: gestational age in weeks
    malform: presence of malformations that could affect weight (0 = absent, 1 = present)
    menarche: mother’s age at menarche (years)
    mheigth: mother’s height (inches)
    momage: mother’s age at delivery (years)
    mrace: mother’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other)
    parity: number of live births prior to this pregnancy
    pnumlbw: previous number of low birth weight babies
    pnumgsa: number of prior small for gestational age babies
    ppbmi: mother’s pre-pregnancy BMI
    ppwt: mother’s pre-pregnancy weight (pounds)
    smoken: average number of cigarettes smoked per day during pregnancy
    wtgain: mother’s weight gain during pregnancy (pounds)

Load and clean the data for regression analysis (i.e. convert numeric to factor where appropriate, check for missing data, etc.).

Propose a regression model for birthweight. This model may be based on a hypothesized structure for the factors that underly birthweight, on a data-driven model-building process, or a combination of the two. Describe your modeling process and show a plot of model residuals against fitted values – use add\_predictions and add\_residuals in making this plot.

Compare your model to two others:

    One using length at birth and gestational age as predictors (main effects only)
    One using head circumference, length, sex, and all interactions (including the three-way interaction) between these

Make this comparison in terms of the cross-validated prediction error; use crossv\_mc and functions in purrr as appropriate.

Note that although we expect your model to be reasonable, model building itself is not a main idea of the course and we don’t necessarily expect your model to be “optimal”.
